require 'yaml'
require 'pathname'
require 'json'
require 'net/http'

module BSDWay
  DATA_DIR = Pathname.new(__dir__).parent.join('data')
  README_PATH = DATA_DIR.parent.join('README.md')
  OLLAMA_URL = 'http://localhost:11434/api/generate'

  def self.start(_args)
    generate
  end

  private_class_method def self.generate
    content = build_readme
    README_PATH.write(content)
    puts "Generated #{README_PATH}"

    commit_and_push
  end

  private_class_method def self.commit_and_push
    status = `git status --porcelain`
    return puts 'No changes to commit' if status.empty?

    system('git add .')
    system('git commit -m "Auto-generate README.md (AI-generated)"')

    if system('git push')
      puts 'Pushed to remote'
    else
      puts 'Warning: Push failed or no remote configured'
    end
  end

  private_class_method def self.build_readme
    cloud_providers = YAML.load_file(DATA_DIR.join('cloud_providers.yml'))
    sites = YAML.load_file(DATA_DIR.join('sites.yml'))
    operating_systems = YAML.load_file(DATA_DIR.join('operating_systems.yml'))
    youtube_channels = YAML.load_file(DATA_DIR.join('youtube_channels.yml'))

    build_prompt = <<~PROMPT
      Generate a well-structured README.md for a BSD resources repository.

      IMPORTANT: Include a prominent header at the very top of the README that clearly states "This README is auto-generated by AI."

      IMPORTANT: Keep the output compact and concise while still providing all relevant data. Avoid verbose explanations - use bullet points and brief notes where possible.

      Include a title, brief description, table of contents, and the following sections:
      - Cloud Providers (with notes about BSD versions and verification dates)
      - Sites
      - Operating Systems (with notes about compatibility)
      - YouTube Channels

      Format it nicely with markdown. Use the data below:

      ## Data

      ### Cloud Providers
      #{cloud_providers.inspect}

      ### Sites
      #{sites.inspect}

      ### Operating Systems
      #{operating_systems.inspect}

      ### YouTube Channels
      #{youtube_channels.inspect}
    PROMPT

    call_ollama(build_prompt).strip
  end

  private_class_method def self.call_ollama(prompt)
    uri = URI(OLLAMA_URL)
    request = Net::HTTP::Post.new(uri)
    request['Content-Type'] = 'application/json'
    request.body = JSON.generate({
                                   model: 'llama3.2:3b',
                                   prompt: prompt,
                                   stream: false
                                 })

    response = Net::HTTP.start(uri.host, uri.port) do |http|
      http.request(request)
    end

    JSON.parse(response.body)['response']
  end
end
